export const team = [
  {
    order: 1,
    name: "Ahsan Habib",
    designation: "Founder & CEO",
    social: [
      "https://www.linkedin.com/in/ahsan577/",
      "https://www.facebook.com/ahsan.habib577",
      "#",
      "#",
      "#",
      "#",
    ],
    image: "/team/habib.jpg",
    id: "1",
  },
  {
    order: 2,
    id: "2",
    image: "/team/alamgir.jpg",
    name: "Alamgir Ahamed",
    designation: "Chief Technology Officer",
    social: [
      "https://www.linkedin.com/in/alamgir-ahamed-7b4b1b1b0",
      "https://www.facebook.com/alamgir.ahamed.dev",
      "#",
      "#",
      "#",
      "#",
    ],
  },

  {
    order: 3,
    designation: "Advisor",
    id: "12",
    name: "Sudip Majumder",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 5,
    id: "5",
    social: ["#", "#", "#", "#", "#"],
    name: "MST Atika ",
    image: "/team/placeholder.png",
    designation: "UI /UX Designer",
  },

  {
    designation: "Director & Talent acquisition Specialist",
    order: 6,
    image: "/team/placeholder.png",
    id: "6",
    social: ["#", "#", "#", "#", "#"],
    name: "Salvia Benazir",
  },
  {
    image: "/team/placeholder.png",
    order: 8,
    designation: "Ai Engineer",
    id: "8",
    name: "Nazmius Sakib",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 8,
    designation: "Fullstack Developer",
    id: "8",
    name: "Md. Iqbal Hossen",
    image: "/team/iqbal.jpg",
    social: ["#", "#", "#", "#", "#"],
  },

  {
    order: 10,
    designation: "Frontend Developer",
    id: "10",
    name: "Jobayer Ahmed",
    image: "/team/jobayer.jpg",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 11,
    designation: "Executive Assistant",
    id: "11",
    name: "Arpan Das",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  //
  {
    name: "Barrister Riazuddin",
    id: "17",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
    order: 17,
    designation: "Legal Advisor",
  },
  {
    social: ["#", "#", "#", "#", "#"],
    order: 18,
    image: "/team/placeholder.png",
    name: "Barrister Sm Saad",
    id: "18",
    designation: "Legal Consultant",
  },
  {
    social: ["#", "#", "#", "#", "#"],
    order: 19,
    designation: "Legal Advisor",
    id: "19",
    image: "/team/placeholder.png",
    name: "Barrister Shanjid Siddique",
  },
  {
    social: ["#", "#", "#", "#", "#"],
    id: "20",
    order: 20,
    name: "Advocate Obayed Enam",
    image: "/team/placeholder.png",
    designation: "Legal Advisor",
  },
];
